version: 2
updates:
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      dev-security:
        dependency-type: "development"
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
      prod-security:
        dependency-type: "production"
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
