name: Setup
description: Setup Python & Poetry

inputs:
  python-version:
    description: The Python version to install
    required: true

runs:
  using: composite
  steps:
    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: poetry
  
    - name: Install Poetry
      if: ${{ steps.cached-poetry.outputs.cache-hit != 'true' }}
      uses: snok/install-poetry@v1

    - name: Setup Python (${{ inputs.python-version }})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry

    - name: Set Poetry environment
      shell: bash
      run: poetry env use ${{ inputs.python-version }}
