name: Setup
description: Setup Python & Poetry

inputs:
  python-version:
    description: The Python version to install
    required: true

runs:
  using: composite
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Setup Python (${{ inputs.python-version }})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
