version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  commands:
    - pip install poetry
    - poetry install --with docs
    - poetry run sphinx-build ./docs $READTHEDOCS_OUTPUT/html
