version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install poetry
    - poetry install --with docs
    - poetry run sphinx-build ./docs ./readthedocs/html
