name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup Poetry
        uses: ./.github/actions/setup
        with:
          python-version: "3.12"

      - name: Release
        uses: corentin-regent/poetrel@v1
        with:
          changelog: CHANGELOG.rst
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          setup-poetry: false
