name: Setup

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  setup:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Setup Python (${{ inputs.python-version }})
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
