name: Test

on:
  workflow_call:
    inputs:
      coverage:
        required: false
        type: boolean
        default: false
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 10

jobs:
  test:
    name: Test (${{ inputs.python-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install test dependencies
        run: poetry install --no-interaction --no-root --with test --without dev

      - name: Install coverage dependencies
        if: inputs.coverage
        run: poetry install --no-interaction --no-root --with coverage --without dev

      - name: Run tests
        if: ${{ !inputs.coverage }}
        run: poetry run pytest -v tests/

      - name: Run tests with coverage
        if: inputs.coverage
        run: poetry run coverage run -m pytest -v tests/

      - name: Generate coverage report
        if: inputs.coverage
        run: poetry run coverage xml -i

      - name: Fix coverage report paths
        if: inputs.coverage
        # see https://community.sonarsource.com/t/sonar-on-github-actions-with-python-coverage-source-issue/36057
        run: sed -i "s/home\/runner\/work\/rate-control\/rate-control/github\/workspace/g" coverage.xml

      - name: Upload coverage artifact
        if: inputs.coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ inputs.python-version }}
          path: coverage.xml
