name: Test

on:
  workflow_call:
    inputs:
      coverage:
        required: false
        type: boolean
        default: false
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 10

jobs:
  test:
    name: Test (Python ${{ inputs.python-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install test dependencies
        run: poetry install --no-interaction --no-root --only test

      - name: Install coverage dependencies
        run: poetry install --no-interaction --no-root --only coverage

      - name: Run tests
        if: ${{ !inputs.coverage }}
        run: poetry run pytest tests/

      - name: Run tests with coverage
        if: inputs.coverage
        run: poetry run coverage -m pytest tests/

      - name: Generate coverage report
        if: inputs.coverage
        run: poetry run coverage xml -o coverage-${{ inputs.python-version }}.xml

      - name: Upload artifact
        if: inputs.coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ inputs.python-version }}
          path: coverage-${{ inputs.python-version }}.xml
