name: Type Checking

on:
  pull_request:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/actions/setup/action.yml"
      - ".github/workflows/type-check.yml"

jobs:
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with test,type-check

      - name: Run type checking
        uses: tsuyoshicho/action-mypy@v4
        with:
          execute_command: poetry run mypy
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
